# Numpy_Assignment_2:

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output:

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [35]:
import numpy as np
arr1d = np.arange(10)
arr2d = arr1d.reshape(2,5)

print("Original 1D array:\n", arr1d)
print("Converted 2D array:\n", arr2d)

Original 1D array:
 [0 1 2 3 4 5 6 7 8 9]
Converted 2D array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output:

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [29]:
arr1 = np.arange(10).reshape(2,5)
arr2 = np.ones(10).reshape(2,5).astype("int32")
vert_stack = np.vstack((arr1, arr2))

print("1st array:\n", arr1)
print("\n2nd array:\n", arr2)
print("\nVertical stack of 1st and 2nd array:\n", vert_stack)

1st array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

2nd array:
 [[1 1 1 1 1]
 [1 1 1 1 1]]

Vertical stack of 1st and 2nd array:
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Question:3

### How to stack two arrays horizontally?

#### Desired Output:

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [44]:
arr1 = np.arange(10).reshape(2,5)
arr2 = np.ones(10).reshape(2,5).astype("int32")
horz_stack = np.hstack((arr1, arr2))

print("1st array:\n", arr1)
print("\n2nd array:\n", arr2)
print("\nHorizontal stack of 1st and 2nd array:\n", horz_stack)

1st array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

2nd array:
 [[1 1 1 1 1]
 [1 1 1 1 1]]

Horizontal stack of 1st and 2nd array:
 [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output:

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
arr = np.array([[0,1,2,3,4],[5,6,7,8,9]])
print("Flat 1d array:", arr.ravel())

Flat 1d array: [0 1 2 3 4 5 6 7 8 9]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output:

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

In [75]:
arr = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])
print("1d array:", arr.ravel())

1d array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output:

array([[ 0, 1, 2],
[ 3, 4, 5],
[ 6, 7, 8],
[ 9, 10, 11],
[12, 13, 14]])

In [83]:
arr = np.arange(15)
arr = arr.reshape(5,3)
print(arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


## Question:7

Create 5x5 an array and find the square of an array?

In [119]:
arr = np.arange(25).reshape(5,5)

print("5x5 array:\n", arr)
print("\nSquare of array:\n",np.square(arr))

5x5 array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Square of array:
 [[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


## Question:8

Create 5x6 an array and find the mean?

In [120]:
arr = np.arange(30).reshape(5,6)
print("5x6 array:\n", arr)
print("\nMean of array:\n",np.mean(arr))

5x6 array:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]

Mean of array:
 14.5


## Question:9

Find the standard deviation of the previous array in Q8?

In [121]:
print("Standard deviation:", np.std(arr))

Standard deviation: 8.65544144839919


## Question:10

Find the median of the previous array in Q8?

In [101]:
print("Median of array:", np.median(arr))

Median of array: 14.5


## Question:11

Find the transpose of the previous array in Q8?

In [122]:
print("Transpose of array:\n", np.transpose(arr))

Transpose of array:
 [[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


## Question:12

Create a 4x4 an array and find the sum of diagonal elements?

In [148]:
arr = np.arange(16).reshape(4,4)

print("4x4 array:\n", arr)
print("\nDiagonal of array:", np.diag(arr))
print("\nSum of diagonal:", np.trace(arr))

4x4 array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Diagonal of array: [ 0  5 10 15]

Sum of diagonal: 30


## Question:13

Find the determinant of the previous array in Q12?

In [153]:
print("Determinant of array:", np.linalg.det(arr))

Determinant of array: -2.9582283945787796e-30


## Question:14

Find the 5th and 95th percentile of an array?

In [178]:
arr = np.arange(50).reshape(5,10)
print("Array:\n", arr)
print("\n5th percentile of array:", np.percentile(arr, 5))
print("95th percentile of array:", np.percentile(arr, 95))

Array:
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]

5th percentile of array: 2.45
95th percentile of array: 46.55


## Question:15

How to find if a given array has any null values?

In [200]:
arr = np.array([1,2,np.nan,4,np.nan])
print("Array with null values:", arr)
print("Array indicating null values:", np.isnan(arr))

Array with null values: [ 1.  2. nan  4. nan]
Array indicating null values: [False False  True False  True]
